# Generated by Django 6.0.1 on 2026-01-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_flowerplan_hash_recipient_first_name_and_more"),
        ("payments", "0003_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="flower_plan",
            field=models.ForeignKey(
                help_text="The flower plan this payment is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="events.flowerplan",
            ),
        ),
    ]
