# Generated by Django 6.0.1 on 2026-02-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="source_partner",
        ),
    ]
