# Generated by Django 6.0.1 on 2026-02-12 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referred_by_partner",
            field=models.ForeignKey(
                blank=True,
                help_text="The partner who referred this user via discount code.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_users",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="source_partner",
            field=models.ForeignKey(
                blank=True,
                help_text="The delivery partner through whose link this user registered.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sourced_users",
                to="partners.partner",
            ),
        ),
    ]
