# Generated by Django 6.0.1 on 2026-02-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0004_termsacceptance"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="agreed_to_terms",
        ),
        migrations.AddField(
            model_name="user",
            name="accepted_terms",
            field=models.ManyToManyField(
                blank=True,
                related_name="accepting_users",
                through="data_management.TermsAcceptance",
                to="data_management.termsandconditions",
            ),
        ),
    ]
