# Generated by Django 6.0.1 on 2026-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                help_text="The user's Stripe Customer ID.",
                max_length=255,
                null=True,
            ),
        ),
    ]
