# Generated by Django 6.0 on 2026-07-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="anonymized_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hash_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hash_first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hash_last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp of when the account was deleted.",
                null=True,
            ),
        ),
    ]
