# Generated by Django 6.0.1 on 2026-02-24 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        help_text="The date the flower delivery will occur."
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Custom message for this specific delivery.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ordered", "Ordered"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        help_text="The status of the delivery.",
                        max_length=20,
                    ),
                ),
                ("ordered_at", models.DateTimeField(blank=True, null=True)),
                ("ordering_evidence_text", models.TextField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_evidence_text", models.TextField(blank=True, null=True)),
                (
                    "commission_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Snapshotted commission amount for this delivery, set at creation.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["delivery_date"],
            },
        ),
        migrations.CreateModel(
            name="FlowerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("tagline", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="OrderBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending_payment",
                        help_text="The current status of the order.",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="The three-letter ISO currency code.",
                        max_length=3,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The budget per bouquet.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Output of the pricing formula before discounts/tax.",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="The discount amount applied to this order.",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax amount (placeholder for future use).",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The final total amount for the plan, auto-computed on save.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("bi-annually", "Bi-Annually"),
                            ("annually", "Annually"),
                        ],
                        help_text="How often deliveries are made.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "recipient_first_name",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's first name.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "hash_recipient_first_name",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                (
                    "recipient_last_name",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's last name.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "hash_recipient_last_name",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True
                    ),
                ),
                (
                    "recipient_street_address",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's street address.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "recipient_suburb",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's suburb or neighborhood.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recipient_city",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's city.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recipient_state",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's state, province, or region.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recipient_postcode",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's postal code.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "recipient_country",
                    models.CharField(
                        blank=True,
                        help_text="Recipient's country.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "delivery_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes to provide more context about the order.",
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the plan's deliveries begin.",
                        null=True,
                    ),
                ),
                (
                    "preferred_delivery_time",
                    models.CharField(
                        blank=True,
                        help_text="Preferred time window for deliveries (e.g., 'morning', 'afternoon').",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flower_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about flower preferences.",
                        null=True,
                    ),
                ),
                (
                    "draft_card_messages",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Staging area for card messages before payment. Keyed by delivery index (e.g. {'0': 'Happy Birthday!'}). Consumed when events are created on payment.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "orderbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.orderbase",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="The ID from Stripe for managing the subscription.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "subscription_message",
                    models.TextField(
                        blank=True,
                        help_text="A single message to be included with all deliveries.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
            },
            bases=("events.orderbase",),
        ),
        migrations.CreateModel(
            name="UpfrontPlan",
            fields=[
                (
                    "orderbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.orderbase",
                    ),
                ),
                (
                    "years",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The total number of years for the plan.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Upfront Plan",
                "verbose_name_plural": "Upfront Plans",
            },
            bases=("events.orderbase",),
        ),
    ]
