# Generated by Django 6.0.1 on 2026-01-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        help_text="The date the flower delivery will occur."
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Custom message for this specific delivery.",
                        null=True,
                    ),
                ),
                (
                    "bouquet_preference",
                    models.CharField(
                        blank=True,
                        help_text="User's preference for the bouquet (e.g., 'Sunflowers').",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        help_text="The status of the delivery.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["delivery_date"],
            },
        ),
        migrations.CreateModel(
            name="FlowerPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the plan is active. Activated upon successful payment.",
                    ),
                ),
                (
                    "recipient_details",
                    models.JSONField(
                        blank=True,
                        help_text="Recipient's details like name, address, etc.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes to provide more context about the plan.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dates",
                    models.JSONField(help_text="The selected dates for delivery."),
                ),
                (
                    "times_per_year",
                    models.PositiveIntegerField(
                        help_text="Number of deliveries per year."
                    ),
                ),
                (
                    "number_of_years",
                    models.PositiveIntegerField(
                        help_text="Total number of years for the plan."
                    ),
                ),
                (
                    "budget_per_bouquet",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The budget for each individual bouquet.",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The final total amount for the plan.",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd",
                        help_text="The three-letter ISO currency code.",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
