# Generated by Django 6.0.1 on 2026-02-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderbase",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                help_text="The discount code applied to this order.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="partners.discountcode",
            ),
        ),
        migrations.AddField(
            model_name="orderbase",
            name="preferred_flower_types",
            field=models.ManyToManyField(
                blank=True, related_name="preferred_orders", to="events.flowertype"
            ),
        ),
    ]
