# Generated by Django 6.0.1 on 2026-02-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Discount",
        ),
    ]
