# Generated by Django 6.0.1 on 2026-07-17 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                help_text="The user who owns this order.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="order",
            field=models.ForeignKey(
                help_text="The order this event belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.order",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkout_session",
                to="events.order",
            ),
        ),
    ]
