# Generated by Django 6.0.1 on 2026-02-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderbase",
            name="preferred_colors",
        ),
        migrations.RemoveField(
            model_name="orderbase",
            name="rejected_colors",
        ),
        migrations.RemoveField(
            model_name="orderbase",
            name="rejected_flower_types",
        ),
        migrations.AddField(
            model_name="orderbase",
            name="flower_notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes about flower preferences.",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Color",
        ),
    ]
