# Generated by Django 6.0.1 on 2026-01-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "hex_code",
                    models.CharField(
                        blank=True, help_text="e.g., #FFFFFF", max_length=7
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlowerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="preferred_colors",
            field=models.ManyToManyField(
                blank=True, related_name="preferred_plans", to="events.color"
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="rejected_colors",
            field=models.ManyToManyField(
                blank=True, related_name="rejected_plans", to="events.color"
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="preferred_flower_types",
            field=models.ManyToManyField(
                blank=True, related_name="preferred_plans", to="events.flowertype"
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="rejected_flower_types",
            field=models.ManyToManyField(
                blank=True, related_name="rejected_plans", to="events.flowertype"
            ),
        ),
    ]
