# Generated by Django 6.0.1 on 2026-01-29 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "orderbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.orderbase",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="The date of the first delivery.",
                        null=True,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The budget per bouquet for each delivery.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("bi-annually", "Bi-Annually"),
                            ("annually", "Annually"),
                        ],
                        help_text="How often deliveries are made.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "price_per_delivery",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The calculated cost for each billing cycle (budget + service fee).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="The ID from Stripe for managing the subscription.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "subscription_message",
                    models.TextField(
                        blank=True,
                        help_text="A single message to be included with all deliveries.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
            },
            bases=("events.orderbase",),
        ),
    ]
