# Generated by Django 6.0.1 on 2026-02-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
        ("partners", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderbase",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="The discount amount applied to this order.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="orderbase",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                help_text="The discount code applied to this order.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="partners.discountcode",
            ),
        ),
        migrations.AddField(
            model_name="orderbase",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Output of the pricing formula before discounts/tax.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="orderbase",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tax amount (placeholder for future use).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="orderbase",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The final total amount for the plan, auto-computed on save.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
