# Generated by Django 6.0.1 on 2026-02-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderbase",
            name="hash_recipient_street_address",
        ),
    ]
