# Generated by Django 6.0 on 2026-07-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="hash_recipient_first_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="hash_recipient_last_name",
        ),
    ]
