# Generated by Django 6.0.1 on 2026-01-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_color_flowertype_flowerplan_preferred_colors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowerplan",
            name="budget",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The budget per bouquet.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="deliveries_per_year",
            field=models.PositiveIntegerField(
                default=1, help_text="How many deliveries are scheduled per year."
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="number_of_years",
            field=models.PositiveIntegerField(
                default=1, help_text="The total number of years for the plan."
            ),
        ),
    ]
