# Generated by Django 6.0.1 on 2026-01-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_flowerplan_budget_alter_flowerplan_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowerplan",
            name="currency",
            field=models.CharField(
                blank=True,
                default="USD",
                help_text="The three-letter ISO currency code.",
                max_length=3,
                null=True,
            ),
        ),
    ]
