# Generated by Django 6.0.1 on 2026-02-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_orderbase_preferred_colors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderbase",
            name="draft_card_messages",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Staging area for card messages before payment. Keyed by delivery index (e.g. {'0': 'Happy Birthday!'}). Consumed when events are created on payment.",
            ),
        ),
    ]
