# Generated by Django 6.0.1 on 2026-07-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tax_amount",
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Output of the pricing formula before discounts.",
                max_digits=10,
            ),
        ),
    ]
