# Generated by Django 6.0.1 on 2026-02-17 20:32

from django.db import migrations


def populate_subtotal(apps, schema_editor):
    from django.db.models import F
    OrderBase = apps.get_model('events', 'OrderBase')
    OrderBase.objects.filter(total_amount__isnull=False).update(subtotal=F('total_amount'))


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_orderbase_discount_amount_orderbase_discount_code_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_subtotal, migrations.RunPython.noop),
    ]
