# Generated by Django 6.0.1 on 2026-01-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_subscriptionplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "Weekly"),
                    ("fortnightly", "Fortnightly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("bi-annually", "Bi-Annually"),
                    ("annually", "Annually"),
                ],
                help_text="How often deliveries are made.",
                max_length=20,
                null=True,
            ),
        ),
    ]
