# Generated by Django 6.0.1 on 2026-02-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="delivery_evidence_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="ordered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="ordering_evidence_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("ordered", "Ordered"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                help_text="The status of the delivery.",
                max_length=20,
            ),
        ),
    ]
