# Generated by Django 6.0.1 on 2026-01-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_subscriptionplan_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="bouquet_preference",
        ),
    ]
