# Generated by Django 6.0.1 on 2026-01-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_flowerplan_budget_flowerplan_deliveries_per_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flowerplan",
            old_name="number_of_years",
            new_name="years",
        ),
    ]
