# Generated by Django 6.0.1 on 2026-07-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_order_hash_recipient_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(
                default="AUD",
                help_text="The three-letter ISO currency code.",
                max_length=3,
            ),
        ),
    ]
