# Generated by Django 6.0.1 on 2026-07-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_orderbase_billing_mode_recurring_preferences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upfrontplan",
            name="orderbase_ptr",
        ),
        migrations.DeleteModel(
            name="SubscriptionPlan",
        ),
        migrations.DeleteModel(
            name="UpfrontPlan",
        ),
        migrations.AddField(
            model_name="orderbase",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="The ID from Stripe for managing a recurring order's subscription.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderbase",
            name="subscription_message",
            field=models.TextField(
                blank=True,
                help_text="A single message to be included with all recurring deliveries.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderbase",
            name="years",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The total number of years for a prepaid plan.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderbase",
            name="billing_mode",
            field=models.CharField(
                choices=[
                    ("one_time", "One-time"),
                    ("recurring", "Recurring"),
                    ("prepaid", "Prepaid"),
                ],
                default="one_time",
                help_text="How this order is billed: one-time, recurring, or prepaid.",
                max_length=20,
            ),
        ),
    ]
