# Generated by Django 6.0.1 on 2026-02-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_orderbase_draft_card_messages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="price_per_delivery",
        ),
        migrations.RemoveField(
            model_name="upfrontplan",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="orderbase",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The final total amount for the plan (budget + fees).",
                max_digits=10,
                null=True,
            ),
        ),
    ]
