# Generated by Django 6.0.1 on 2026-01-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_flowerplan_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowerplan",
            name="currency",
            field=models.CharField(
                default="USD",
                help_text="The three-letter ISO currency code.",
                max_length=3,
            ),
        ),
    ]
