# Generated by Django 6.0.1 on 2026-07-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_remove_upfrontplan_orderbase_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderbase",
            name="years",
        ),
        migrations.AlterField(
            model_name="orderbase",
            name="billing_mode",
            field=models.CharField(
                choices=[("one_time", "One-time"), ("recurring", "Recurring")],
                default="one_time",
                help_text="How this order is billed: one-time or recurring.",
                max_length=20,
            ),
        ),
    ]
