# Generated by Django 6.0.1 on 2026-02-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_remove_subscriptionplan_price_per_delivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowertype",
            name="tagline",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
