# Generated by Django 6.0.1 on 2026-01-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_remove_event_bouquet_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderbase",
            name="delivery_notes",
            field=models.TextField(
                blank=True,
                help_text="Any specific instructions or notes for the delivery personnel.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderbase",
            name="preferred_delivery_time",
            field=models.CharField(
                blank=True,
                help_text="Preferred time window for delivery (e.g., 'morning', 'afternoon', '10 AM - 12 PM').",
                max_length=255,
                null=True,
            ),
        ),
    ]
