# Generated by Django 6.0.1 on 2026-01-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_rename_number_of_years_flowerplan_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowerplan",
            name="currency",
            field=models.CharField(
                default="usd",
                help_text="The three-letter ISO currency code.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The final total amount for the plan.",
                max_digits=10,
            ),
        ),
        migrations.DeleteModel(
            name="Price",
        ),
    ]
