# Generated by Django 6.0.1 on 2026-01-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_flowerplan_currency_flowerplan_total_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowerplan",
            name="recipient_details",
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="recipient_city",
            field=models.CharField(
                blank=True, help_text="Recipient's city.", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="recipient_country",
            field=models.CharField(
                blank=True, help_text="Recipient's country.", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="recipient_first_name",
            field=models.CharField(
                blank=True,
                help_text="Recipient's first name.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="recipient_last_name",
            field=models.CharField(
                blank=True,
                help_text="Recipient's last name.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="recipient_postcode",
            field=models.CharField(
                blank=True,
                help_text="Recipient's postal code.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="recipient_state",
            field=models.CharField(
                blank=True,
                help_text="Recipient's state, province, or region.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="recipient_street_address",
            field=models.CharField(
                blank=True,
                help_text="Recipient's street address.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="flowerplan",
            name="recipient_suburb",
            field=models.CharField(
                blank=True,
                help_text="Recipient's suburb or neighborhood.",
                max_length=100,
                null=True,
            ),
        ),
    ]
