# Generated by Django 6.0.1 on 2026-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_orderbase_delivery_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderbase",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="orderbase",
            name="preferred_delivery_time",
        ),
        migrations.AlterField(
            model_name="orderbase",
            name="delivery_notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes to provide more context about the order.",
                null=True,
            ),
        ),
    ]
