# Generated by Django 6.0.1 on 2026-07-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_orderbase_years_alter_orderbase_billing_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderbase",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "Weekly"),
                    ("fortnightly", "Fortnightly"),
                    ("monthly", "Monthly"),
                    ("annually", "Annually"),
                ],
                help_text="How often deliveries are made.",
                max_length=20,
                null=True,
            ),
        ),
    ]
