# Generated by Django 6.0.1 on 2026-01-31 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_remove_orderbase_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleDeliveryPlan",
            fields=[
                (
                    "orderbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="events.orderbase",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The budget for the single bouquet.",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The final total amount for this single-delivery delivery, including fees.",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "One-Time Plan",
                "verbose_name_plural": "One-Time Plans",
            },
            bases=("events.orderbase",),
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="upfrontplan",
            name="start_date",
        ),
        migrations.AddField(
            model_name="orderbase",
            name="preferred_delivery_time",
            field=models.CharField(
                blank=True,
                help_text="Preferred time window for deliveries (e.g., 'morning', 'afternoon').",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderbase",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="The date the plan's deliveries begin.", null=True
            ),
        ),
    ]
