# Generated by Django 6.0.1 on 2026-02-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_singledeliveryplan_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="singledeliveryplan",
            options={
                "verbose_name": "Single-Delivery Plan",
                "verbose_name_plural": "Single-Delivery Plans",
            },
        ),
        migrations.AlterField(
            model_name="singledeliveryplan",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The budget for the single bouquet.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="singledeliveryplan",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The final total amount for this single-delivery delivery, including fees.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
