# Generated by Django 6.0.1 on 2026-07-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_checkoutsession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderbase",
            name="preferred_flower_types",
        ),
        migrations.DeleteModel(
            name="FlowerType",
        ),
    ]
