# Generated by Django 6.0.1 on 2026-02-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_singledeliveryplan_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderbase",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending_payment",
                help_text="The current status of the order.",
                max_length=20,
            ),
        ),
    ]
