# Generated by Django 6.0.1 on 2026-07-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_simplify_card_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderbase",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Delivery fee, auto-computed on save. Zero once the budget reaches the threshold, where delivery comes out of the budget.",
                max_digits=10,
            ),
        ),
    ]
