# Generated by Django 6.0.1 on 2026-02-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_add_cancelled_refunded_statuses"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SingleDeliveryPlan",
        ),
    ]
