# Generated by Django 6.0.1 on 2026-02-18 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="The email address to block.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the email was added to the blocklist.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked Email",
                "verbose_name_plural": "Blocked Emails",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("partner", "Partner"),
                            ("customer", "Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")], max_length=10
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField()),
                ("scheduled_for", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="TermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terms_type",
                    models.CharField(
                        choices=[
                            ("florist", "Florist"),
                            ("customer", "Customer"),
                            ("affiliate", "Affiliate"),
                        ],
                        help_text="The user type these terms apply to.",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version number, e.g., '1.0'", max_length=20
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The full HTML content of the terms and conditions."
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time this version was published.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Terms and Conditions",
                "ordering": ["-published_at"],
            },
        ),
    ]
