# Generated by Django 6.0.1 on 2026-02-24 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_management", "0001_initial"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipient_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="partners.partner",
            ),
        ),
    ]
