# Generated by Django 6.0.1 on 2026-02-24 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_management", "0002_initial"),
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipient_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="termsacceptance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terms_acceptances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="termsandconditions",
            unique_together={("terms_type", "version")},
        ),
        migrations.AddField(
            model_name="termsacceptance",
            name="terms",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acceptances",
                to="data_management.termsandconditions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="termsacceptance",
            unique_together={("user", "terms")},
        ),
    ]
