# Generated by Django 6.0.1 on 2026-02-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="service_radius_km",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.DeleteModel(
            name="ServiceArea",
        ),
    ]
