# Generated by Django 6.0.1 on 2026-02-17 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("partners", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commission",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_requests",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="discountusage",
            name="discount_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usages",
                to="partners.discountcode",
            ),
        ),
        migrations.AddField(
            model_name="discountusage",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_usage",
                to="payments.payment",
            ),
        ),
    ]
