# Generated by Django 6.0.1 on 2026-02-17 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partners", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discountusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="partner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_code",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_requests",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="payoutlineitem",
            name="commission",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payout_line_item",
                to="partners.commission",
            ),
        ),
        migrations.AddField(
            model_name="payoutlineitem",
            name="delivery_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payout_line_item",
                to="partners.deliveryrequest",
            ),
        ),
        migrations.AddField(
            model_name="payoutlineitem",
            name="payout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="partners.payout",
            ),
        ),
    ]
