# Generated by Django 6.0.1 on 2026-02-17 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="code",
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="partner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_code",
                to="partners.partner",
            ),
        ),
    ]
