# Generated by Django 6.0.1 on 2026-02-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("denied", "Denied"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
