# Generated by Django 6.0.1 on 2026-02-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("denied", "Denied"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
