# Generated by Django 6.0.1 on 2026-02-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="booking_slug",
        ),
    ]
