/**
 * Defines the payload structure for creating a new UpfrontPlan.
 * This is typically a subset of UpfrontPlan, excluding fields generated by the backend.
 */
export interface CreateUpfrontPlanPayload {
    budget: number;
    frequency: string;
    years: number;
    recipient_first_name?: string;
    recipient_last_name?: string;
    recipient_street_address?: string;
    recipient_suburb?: string;
    recipient_city?: string;
    recipient_state?: string;
    recipient_postcode?: string;
    recipient_country?: string;
}
