// foreverflower/frontend/src/types/plans.ts

import type { DeliveryEvent } from './events';

/**
 * Defines the structure for a Color object.
 */
export interface Color {
    id: number;
    name: string;
    hex_code: string;
}

/**
 * Defines the structure for a FlowerType object.
 */
export interface FlowerType {
    id: number;
    name: string;
}

/**
 * Defines the comprehensive structure for an UpfrontPlan.
 */
export interface UpfrontPlan {
    id: number;
    user: number;
    status: string; // Changed from is_active: boolean;
    start_date?: string;
    notes: string | null;
    budget: string;
    deliveries_per_year: number;
    years: number;
    total_amount: number;
    currency: string;
    
    recipient_first_name: string | null;
    recipient_last_name: string | null;
    recipient_street_address: string | null;
    recipient_suburb: string | null;
    recipient_city: string | null;
    recipient_state: string | null;
    recipient_postcode: string | null;
    recipient_country: string | null;

    preferred_colors: number[];
    preferred_flower_types: number[];
    rejected_colors: number[];
    rejected_flower_types: number[];
    // Assuming Event interface would be imported from events.ts
    events: DeliveryEvent[]; 
}

/**
 * Defines the payload structure for creating a new UpfrontPlan.
 * This is typically a subset of UpfrontPlan, excluding fields generated by the backend.
 */
export interface CreateUpfrontPlanPayload {
    budget: number;
    deliveries_per_year: number;
    years: number;
    recipient_first_name?: string;
    recipient_last_name?: string;
    recipient_street_address?: string;
    recipient_suburb?: string;
    recipient_city?: string;
    recipient_state?: string;
    recipient_postcode?: string;
    recipient_country?: string;
}

/**
 * Type alias for partial updates to an UpfrontPlan.
 * Makes all properties of UpfrontPlan optional.
 */
export type PartialUpfrontPlan = Partial<UpfrontPlan>;

/**
 * Defines the comprehensive structure for a SubscriptionPlan.
 */
export interface SubscriptionPlan extends UpfrontPlan {
    delivery_frequency_unit: string;
    delivery_frequency_value: number;
    recurring_price: number;
    stripe_customer_id: string | null;
    stripe_subscription_id: string | null;
    frequency: string;
    price_per_delivery: number;
    subscription_message: string | null;
}

/**
 * Type alias for partial updates to a SubscriptionPlan.
 * Makes all properties of SubscriptionPlan optional.
 */
export type PartialSubscriptionPlan = Partial<SubscriptionPlan>;